# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Orbit 360 Facetracking' do

	pod 'OpenCV'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'VideoCore', :git => 'https://github.com/jgh-/VideoCore', :branch => 'master'

end

target 'Orbit 360 FacetrackingTests' do

end

target 'Orbit 360 FacetrackingUITests' do

end

